# Generated by Django 6.0.3 on 2026-04-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
