# Generated by Django 6.0.3 on 2026-04-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz_manager', '0003_question_created_at_question_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_title',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='url',
            new_name='video_url',
        ),
    ]
